APP/APP/urls.py
from django.contrib import admin
from django.urls import path, include
from app_promo.admin import blog_site

urlpatterns = [
    path("admin/", blog_site.urls),
    path("admin/", admin.site.urls),
    path("", include('app_promo.url')),
]

APP/app_promo/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    total_points = models.FloatField(default=0)
    is_admin = models.BooleanField(default=False)


class AdminUser(User):
    def save(self, *args, **kwargs):
        self.is_admin = True
        super().save(*args, **kwargs)

    def get_login_redirect_url(self):

        return reverse('admin_page')


class App(models.Model):
    choices = [
        ("SN", "Social Networking"),
        ("ENT", "Entertainment"),
        ("PROD", "Productivity"),
        ("EDU", "Education"),
        ("FIT", "Health & Fitness"),
        ("TRAV", "Travel"),
        ("FIN", "Finance"),
        ("NEWS", "News & Magazines"),
        ("MUSIC", "Music"),
        ("PHOTO", "Photography"),
        ("SHOP", "Shopping"),
        ("GAME", "Games"),
        ("SPORT", "Sports"),
        ("UTIL", "Utilities"),
        ("WEATH", "Weather"),
        ("FOOD", "Food & Drink"),
        ("LIFE", "Lifestyle"),
        ("BUS", "Business"),
    ]

    app_name = models.CharField(max_length=500)
    app_category = models.CharField(max_length=200, choices=choices)
    app_point = models.FloatField(default=0)
    app_icon = models.ImageField(upload_to="app_icon.jpg", default="default.jpg")
    date = models.DateTimeField(default=timezone.now)


# this model handles  screenshot updated by users  user will be only award points if screenshot is updated
class downloadApp(models.Model):
    screenshot = models.ImageField(upload_to="app_icon.jpg")
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # adding point's to user profile  overwriting the save method  since user field is ForeignKey to user field
    # retrieving User model total_point field and adding points
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Add points to the user here
        self.user.total_points += self.app.app_point
        self.user.save()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='app_icon.jpg', default="profile_default.jpg")

APP/app_promo/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import User
from django import forms
from .models import User, AdminUser, App
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}


class CustomAdminForm(UserCreationForm):
    class Meta:
        model = AdminUser
        fields = ("username",)
        field_classes = {"username": UsernameField}


class AppCreateForm(forms.ModelForm):
    class Meta:
        model = App
        fields = ["app_name", "app_category", "app_point", "app_icon"]
        widgets = {
            "app_name": forms.TextInput(attrs={"class": "name"}),
            "app_category": forms.Select(attrs={"class": "category"}),
            "app_point":forms.NumberInput(attrs={"class": "apppoint"}),
            "app_icon":forms.ClearableFileInput(attrs={"class": "icon"})
        }

APP/app_promo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .forms import CustomUserForm, CustomAdminForm, AppCreateForm
from .models import App, downloadApp, User, AdminUser, Profile
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# rest api import
from rest_framework import generics as rest_generics
from .serializers import AppSerializer, AdminSerializer, ProfileSerializer, UserSerializer, downloadAppSerializer
from rest_framework import mixins
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.permissions import BasePermission
from rest_framework.decorators import api_view
from django.contrib import messages
from django import forms


# admin authorisation

class CustomLoginRequiredMixin(AccessMixin):
    """Verify that the current user is authenticated and is the user is an admin user."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_admin:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


# class based views

class UserCreateVIew(generic.CreateView):
    form_class = CustomUserForm
    template_name = "app_promo/signup.html"

    def get_success_url(self):
        return reverse("login")


class AdminUserCreateView(generic.CreateView):
    form_class = CustomAdminForm
    template_name = "app_promo/admin_signup.html"

    def get_success_url(self):
        return reverse("login")


class AppListView(generic.ListView):
    model = App
    template_name = "app_promo/appz_list.html"
    paginate_by = 5
    ordering = ["-date"]


class AppCreateView(CustomLoginRequiredMixin, generic.CreateView):
    form_class = AppCreateForm

    template_name = "app_promo/app_create.html"

    def get_success_url(self):
        return reverse("admin_page")


@login_required
def profile(request):
    return render(request, 'app_promo/profile.html')


@login_required
def completed_tasks(request):
    user = request.user
    completed_apps = downloadApp.objects.filter(user=user)
    return render(
        request, "app_promo/completed_tasks.html", {"completed_apps": completed_apps}
    )


@login_required
def upload_document(request, pk):
    app = get_object_or_404(App, pk=pk)  # Retrieve the app based on the provided pk

    if request.method == "POST":
        file = request.FILES.get("file")
        user = request.user  # Assuming the user is authenticated
        # Create a DownloadApp instance and associate it with the user and app
        download_app = downloadApp.objects.create(app=app, user=user, screenshot=file)

        return redirect("profile")
    return render(request, "app_promo/download.html", {"app": app})


# rest api

class IsAdminUser(BasePermission):
    def has_permission(self, request, view):
        return request.user.is_authenticated and request.user.is_admin


class AppApiCreateView(rest_generics.CreateAPIView):
    permission_classes = (IsAdminUser,)
    serializer_class = AppSerializer
    queryset = App.objects.all()


class AppApiListView(rest_generics.ListAPIView):
    serializer_class = AppSerializer
    queryset = App.objects.all()


class AdminUserListView(rest_generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = AdminSerializer

    def get_queryset(self):
        user = self.request.user
        return AdminUser.objects.filter(username=user.username)


class AdminUserApiCreateView(rest_generics.CreateAPIView):
    serializer_class = AdminSerializer


class UserApiCreateView(rest_generics.CreateAPIView):
    serializer_class = UserSerializer


class UserApiListView(rest_generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        user = self.request.user
        return User.objects.filter(username=user.username)


# updateing screenshot


class DownloadAppApi(rest_generics.CreateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = downloadAppSerializer
    queryset = downloadApp.objects.all()

    def perform_create(self, serializer):
        # Set the user field as the authenticated user
        serializer.save(user=self.request.user)


class DownloadAppListApi(rest_generics.ListAPIView):
    serializer_class = downloadAppSerializer
    queryset = downloadApp.objects.all()


class CompletedTaskListApi(rest_generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = downloadAppSerializer

    def get_queryset(self):
        user = self.request.user
        return downloadApp.objects.filter(user=user)



class ProfileCreateListApi(rest_generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ProfileSerializer
    queryset = Profile.objects.all()

    def get_queryset(self):
        user = self.request.user
        return Profile.objects.filter(user=user)

APP/app_promo/templates/app_promo/admin_base.html
{% load static %}
<DOCTYPE html>
    <html lang="en">
        <head>
            <link rel="stylesheet" href="{% static 'app_promo/main.css' %}">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

            
            <meta charset="UTF-8">
            <meta name="description" content="admin page">
            <title>{%block a %}{% endblock %}</title>

        </head>
        <body>
            <header>
                <nav class="admin-nav">
                    <ul>
                        
                        <li><a href="{% url 'list' %}">View site</a></li>|
                    {% if user.is_authenticated %}  
                        <li><a href="{% url  'logout' %}">Logout</a></li>|
                    {% else %}
                       <li><a href="href="{%  url 'login' %}"">Log In</a></li>| 
                    {% endif %} 
                    <li class="create"><a href="{% url 'admin_page' %}">Create App</a></li>      
                    </ul>
                </nav>
                <h1 class="hello">HELLO ADMIN </h1>
               
            </header>
            <main>
               {% block b %}
               {% endblock %}
                
            </main>
        </body>
    </html>

APP/app_promo/templates/app_promo/admin_signup.html
{% extends 'app_promo/base.html' %}

{% block a %}signup{% endblock %}

{% block b %}

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button  class="buttonz" type="submit">Signup</button>
</form>

{% endblock %}

APP/app_promo/templates/app_promo/app_create.html
{% extends 'app_promo/admin_base.html'%}
{% load crispy_forms_tags %}


   {%block b%}
   
      <form  class="formzz" method="post">
         {% csrf_token %}
         
            {{form|crispy}}
            
         <button  class="buttonz" type="submit">Create</button>
     </form>
   
    
    {% endblock %}

APP/app_promo/templates/app_promo/appz_list.html
{% extends 'app_promo/base.html' %}

{%block a %}promo{%endblock%}

{% block b %}


   

  <!-- <section class="container">
    <ul>
      {% for object in object_list %}
      <li class="li"><img src="{{object.app_icon.url}}" width="100" height="100" loading="lazy" alt="icon">class="app-name"><a href="#">{{object.app_name}}</a>
        <p class="no-wrap"><span class="app-point">{{object.app_point}}</span> 
          <a class="app-delete"  href="{% url 'upload_document' object.id %}">Upload Screenshot</a></li></p>
        {% endfor %}   
    </ul>
  </section> -->

  <section class="container">
    <ul>
      {% for object in object_list %}

      <li class="box"><img src="{{object.app_icon.url}}" class="app-icon" width=100, height="100" alt="app icon"/><a class="app-name" href="#">{{object.app_name}}</a><span class="app-point">{{object.app_point}}</span>
      <p>{{object.get_app_category_display}}</p><p> <a href="{% url 'upload_document' object.id %}" class="Screenshot">Upload Snapshot</a></p></li>
      <br>
      <br>
      
      {% endfor %}   
    </ul>
  </section>








{% endblock %}

APP/app_promo/templates/app_promo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block a %} {% endblock %}</title>
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
   
    <link rel="stylesheet" href="{% static 'app_promo/main.css' %}">
    
    
</head>
<body>
<header>
    <nav class="admin-nav">
        <ul>
            <li><a href="{% url 'list' %}">Home</a> </li><span class="bar">|</span>
            <li ><a href="{% url 'profile' %}">Profile</a> </li><span class="bar">|</span>
            <li ><a href="{% url 'completed_tasks' %}">Completed Task</a></li><span class="bar">|</span>
            {% if user.is_authenticated %}
               <li class="logout"><a href="{% url 'logout' %}">Logout</a></li>

        {%else%}
            <li class="login"><a href="{% url 'login' %}">Login</a></li>|
            <li class="login"><a href="{% url 'signup' %}">signup</a></li>
        {% endif %} 
        {% if request.user.is_admin%} 
        |<li class="adminpage"><a href="{% url 'admin_page' %}">Admin Page</a></li> 
        {% endif %} 

        </ul>

    
    </nav>
</header>
<main>
    {% block b %} {% endblock %}
</main>

</body>
</html>

APP/app_promo/templates/app_promo/completed_tasks.html
{% extends 'app_promo/base.html' %}

{% block a %}Points Earned{% endblock%}

{% block b %}
  <h2 class="c">Completed Tasks</h2>
  <ul>
    {% for app in completed_apps %}
      <li class="completed">{{ app.app.app_name }} - {{ app.app.app_point }} points</li>
      <br>
    {% empty %}
      <li>No completed tasks found.</li>
    {% endfor %}
  </ul>
{% endblock %}

APP/app_promo/templates/app_promo/download.html
{% extends 'app_promo/base.html' %}
{% load static %}
{% block a %}screenshot{% endblock %}

{% block b %}

<form
  action="{% url 'upload_document' pk=app.pk %}"
  method="post"
  class="dropzone"
  id="MyDropZone"
>
  {% csrf_token %}

  <button class= "buttonz" type="submit" id="upload-button" required >Upload</button>

</form>

<script>
  Dropzone.options.MyDropZone = {
    // Other Dropzone configuration options...
    autoProcessQueue: false
};

document.getElementById("upload-button").addEventListener("click", function() {
    myDropzone.processQueue();
});

</script>

{% endblock %}

APP/app_promo/templates/app_promo/login.html
{% extends 'app_promo/base.html' %}

{% load crispy_forms_tags %}

{% block a %}login{%endblock %} 

{% block b %}

<form method="POST">
  {% csrf_token%}
  {{form|crispy}}
  <button class="buttonz" type="submit">Login</button>

</form>
<h2><a href="{% url 'signup' %}">don't have a account click here to signin</a></h2>

{% endblock %}

APP/app_promo/templates/app_promo/logout.html
{% extends 'app_promo/base.html' %}

{%block a %}logout{%endblock%}

{% block b %}

    
    <h1>You have successfully logged out</h1>
   
    <a  class= "login-redrict"href="{%url 'login' %}">Click here to login again</a>
    



{% endblock %}

APP/app_promo/templates/app_promo/profile.html
{% extends 'app_promo/base.html' %}

{%  load crispy_forms_tags %}

{% block a %}{{user.username}}{% endblock %}



{%block b %}

<div class="profile">
  <div class="profile-picture">
    <img class="profile-image" width="300" height="300" src="{{user.profile.image.url }}" alt="Profile Picture">
  </div>
  <div class="profile-info">
    <h2 class="Username">Username: {{ user.username }}</h2>
    <h3 class="TOTAL-POINTS">TOTAL POINTS: {{user.total_points}}</h3>
  </div>
</div>


{%endblock%}

APP/app_promo/templates/app_promo/signup.html
{% extends 'app_promo/base.html' %}

{% block a %}signup{% endblock %}

{% block b %}

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="buttonz" type="submit">Signup</button>
</form>

{% endblock %}